version: '3.9'

networks:
    docker-setup-network:

services:
    nginx:
        # image: nginx:stable-alpine
        build:
            context: .
            dockerfile: nginx.Dockerfile
        container_name: ${APP_NAME}-nginx
        depends_on:
            - php
            - mysql
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./bedrock:/var/www/html:delegated
            - ./nginx:/var/log/nginx
        networks:
            - docker-setup-network

    mysql:
        image: mysql:8.0
        container_name: ${APP_NAME}-mysql
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - docker-setup-network

    php:
        # image: php:8.0-fpm-alpine
        build:
            context: .
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME}-php
        depends_on:
            - mysql
        tty: true
        volumes:
            - ./bedrock:/var/www/html:delegated
        networks:
            - docker-setup-network

    wp:
        build:
            context: .
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME}-wp-cli
        depends_on:
            - php
            - mysql
        volumes:
            - ./bedrock:/var/www/html:delegated
        entrypoint: ['wp', '--allow-root']

    composer:
        build:
            context: .
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME}-composer
        volumes:
            - ./bedrock:/var/www/html:delegated
        working_dir: /var/www/html
        depends_on:
            - php
        entrypoint: ['composer']

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}-phpmyadmin
        volumes:
            - ./phpmyadmin/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
        environment:
            PMA_HOST: "${DB_HOST}"
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        ports:
            - '8082:80'
        depends_on:
            - mysql
        links:
            - mysql:mysql
        networks:
            - docker-setup-network